### ISSUE TITLE
Fatal Error when upgrading to PHP 8.2

### ISSUE THREAD

**Issue by advantipro-gmbh** [ThatGerber/dfp-ads#45]
When upgrading to PHP 8.2 I get the error message below (paths slightly cleansed).

Any ideas what the issues is, and how to fix it?

Thanks!

`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /…/wp-content/plugins/dfp-targeting-for-wp/dfp-targeting-for-wp.php:110 Stack trace: #0 /…/wp-includes/class-wp-hook.php(324): dfp_custom_target() #1 /…/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /…/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /…/wp-includes/general-template.php(3052): do_action() #4 /…/wp-content/themes/magazine-news-byte/header.php(7): wp_head() #5 /…/wp-includes/template.php(790): require_once(‘…’) #6 /…/wp-includes/template.php(725): load_template() #7 /…/wp-includes/general-template.php(48): locate_template() #8 /…/wp-content/themes/magazine-news-byte/front-page.php(6): get_header() #9 /…/wp-includes/template-loader.php(106): include(‘…’) #10 /…/wp-blog-header.php(19): require_once(‘…’) #11 /…/index.php(17): require(‘…’) #12 {main} thrown in /…/wp-content/plugins/dfp-targeting-for-wp/dfp-targeting-for-wp.php on line 110`

**Comment by chriswgerber** [comment]
Sorry, that's not related to this plugin. Check the Plugins page within your WP Admin for the plugin. There should be a link that points you to the plugin's homepage or a support page.
